spring:
  data:
    mongodb:
      host: ${host:10.10.10.10}
      port: ${port:27017}
      database: ${db:bookshelf}
  profiles:
    active: production

logging:
  file:
    name: logs/bookshelf.log
