###  REGISTER USER
POST http://localhost:8080/api/register/
Content-Type: application/json

{ "username": "", "password": ""}

### COUNT BOOKS
GET http://localhost:8080/api/count/
Accept: application/json

###

