---
- hosts: 127.0.0.1
  tasks:
    - file: path=/tmp/bookshelf-deploy state=directory
    - copy: src=../target/bookshelf-web-2.0.jar dest=/tmp/bookshelf-deploy/bookshelf.jar
    - copy: src=Dockerfile dest=/tmp/bookshelf-deploy/Dockerfile

    - name: stop and delete obsolete containers
      docker:
        image: sb/bookshelf-web
        name: bookshelf-web
        state: absent

    - name: delete docker image
      docker_image:
        path: /tmp/bookshelf-deploy
        name: sb/bookshelf-web
        state: absent

    - name: build docker image
      docker_image:
        path: /tmp/bookshelf-deploy
        name: sb/bookshelf-web
        state: build

    - name: app container
      docker:
        name: bookshelf-web
        image: sb/bookshelf-web
        restart_policy: always
        state: running
        links:
          - mongo:mongo

    - name: clean
      file:
        state: absent
        path: /tmp/bookshelf-deploy
